-- Matriz de SLA por Cliente/Producto/Nivel.
-- Ejecutá este SQL en el editor SQL de tu proyecto Supabase (SQL Editor > New query).

create table if not exists public.sla_matrix (
  id bigint generated by default as identity primary key,
  comercial text not null default '',
  cliente text not null default '',
  producto text not null default '',
  nivel_emergencia text not null default '',
  descripcion text not null default '',
  tiempo_respuesta_min_minutos int,
  tiempo_respuesta_max_minutos int,
  tiempo_respuesta_raw text not null default '',
  diagnostico_min_horas int,
  diagnostico_max_horas int,
  horario_sla text not null default '',
  created_at timestamptz not null default now(),
  constraint sla_matrix_unique unique (cliente, producto, nivel_emergencia, horario_sla, descripcion)
);

create index if not exists idx_sla_matrix_cliente on public.sla_matrix (cliente);
create index if not exists idx_sla_matrix_producto on public.sla_matrix (producto);

alter table public.sla_matrix enable row level security;

create policy "Allow all for anon on sla_matrix"
  on public.sla_matrix
  for all
  to anon
  using (true)
  with check (true);

