-- Tabla para gestionar tareas pendientes de la Mesa de Ayuda.
-- Ejecutá este SQL en el editor SQL de tu proyecto Supabase (SQL Editor > New query).

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  titulo text not null default '',
  descripcion text not null default '',
  responsable text not null default '',
  prioridad text not null default '',
  estado text not null default 'Pendiente',
  fecha_creacion timestamptz not null default now(),
  fecha_vencimiento timestamptz,
  constraint tasks_titulo_responsable_fecha_creacion_key unique (titulo, responsable, fecha_creacion)
);

alter table public.tasks enable row level security;

create policy "Allow all for anon on tasks"
  on public.tasks
  for all
  to anon
  using (true)
  with check (true);

