-- Tabla para guardar los tickets cargados desde el Excel.
-- Ejecutá este SQL en el editor SQL de tu proyecto Supabase (SQL Editor > New query).

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null,
  cliente text not null default '',
  titulo text not null default '',
  tipo text not null default '',
  autor text not null default '',
  asignado text not null default '',
  prioridad text not null default '',
  estado text not null default '',
  creacion text not null default '',
  modificacion text not null default '',
  constraint tickets_ticket_id_key unique (ticket_id)
);

-- Permitir que la app (anon key) lea y escriba en esta tabla.
-- Ajustá RLS según tu política (ej. solo usuarios autenticados).
alter table public.tickets enable row level security;

create policy "Allow all for anon"
  on public.tickets
  for all
  to anon
  using (true)
  with check (true);
