-- Tabla para gestión de clientes (Bancos): nombre, producto, contrato, contacto.
-- Ejecutá este SQL en el editor SQL de tu proyecto Supabase (SQL Editor > New query).
-- Pensada para extender: podés agregar columnas (ej. contacto_cargo, sitio_web) con ALTER TABLE.

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  nombre text not null default '',
  producto text not null default '',
  fecha_contrato_inicio date,
  fecha_contrato_fin date,
  contacto_nombre text not null default '',
  contacto_email text not null default '',
  contacto_telefono text not null default '',
  notas text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_clients_nombre on public.clients (nombre);

alter table public.clients enable row level security;

create policy "Allow all for anon on clients"
  on public.clients
  for all
  to anon
  using (true)
  with check (true);
